config/routes.rb
Rails.application.routes.draw do
  root 'areas#index'
  resources :areas
  resources :devices, :except => :index

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :devices
  mount_uploader :area_image, AreaImageUploader
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :properties
  belongs_to :area
  mount_uploader :device_image, DeviceImageUploader

  def info
    self.properties.map { |property|
      property.name + ":" + property.value
    }.join('|')
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :device
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :area_image, :area_image_cache, :remove_area_image)
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :x, :y, :z, :device_image, :device_image_cache, :remove_device_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/areas/_form.html.slim
= form_for @area do |f|
  - if @area.errors.any?
    #error_explanation
      h2 = "#{pluralize(@area.errors.count, "error")} prohibited this area from being saved:"
      ul
        - @area.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

  .form-group
    - if @area.area_image?
      .thumbnail
        = image_tag @area.area_image.url
    = f.file_field :area_image
    = f.hidden_field :area_image_cache
    - if @area.area_image?
      .checkbox
        label
          = f.check_box :remove_area_image
          画像を削除する
  .actions = f.submit

app/views/areas/edit.html.slim
h1 Editing area

== render 'form'

= link_to 'Show', @area
'|
= link_to 'Back', areas_path

app/views/areas/index.html.slim
h1 Listing areas

table.table.table-striped.table-bordered
  thead
    tr
      th Name
      th
      th

  tbody
    - @areas.each do |area|
      tr
        td = link_to area.name, area
        td = link_to 'Edit', edit_area_path(area)
        td = link_to 'Destroy', area, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Area', new_area_path

app/views/areas/new.html.slim
h1 New area

== render 'form'

= link_to 'Back', areas_path

app/views/areas/show.html.slim
p#notice = notice

h1= @area.name
#device-map data = { image: @area.area_image.url, chart: @area.devices.map {|device| {x: device.x, y: device.y, name: device.name, url: device_path(device), info: device.info, image: device.device_image.url } }.to_json }
  span#tooltip
    #tooltip-name
    #tooltip-text
    img#product-thumbnail

h1 Listing devices

table.table.table-striped.table-bordered
  thead
    tr
      th
      th Name
      th X
      th Y
      th

  tbody
    - @area.devices.each do |device|
      tr
        td = image_tag device.device_image.url
        td = device.name
        td = device.x
        td = device.y
        td = link_to 'Show', device, class: "btn"

= link_to 'Edit', edit_area_path(@area)
'|
= link_to 'Back', areas_path

app/views/devices/_form.html.slim
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      h2 = "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      ul
        - @device.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :x
    = f.number_field :x, class: "form-control"
  .form-group
    = f.label :y
    = f.number_field :y, class: "form-control"
  .form-group
    = f.label :z
    = f.number_field :z, class: "form-control"
  .form-group
    - if @device.device_image?
      .thumbnail
        = image_tag @device.device_image.url
    = f.file_field :device_image
    = f.hidden_field :device_image_cache
    - if @device.device_image?
      .checkbox
        label
          = f.check_box :remove_device_image
          画像を削除する
  .actions = f.submit

app/views/devices/edit.html.slim
h1 Editing device

== render 'form'

= link_to 'Show', @device
'|
= link_to 'Back', @device.area

app/views/devices/new.html.slim
h1 New device

== render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.slim
p#notice = notice

p
  strong Name:
  = @device.name
p
  strong X:
  = @device.x
p
  strong Y:
  = @device.y
p
  strong Z:
  = @device.z

- if @device.device_image?
  .thumbnail
    = image_tag @device.device_image.url

h1 Listing properties

table.table.table-striped.table-bordered
  thead
    tr
      th Name
      th Value

  tbody
    - @device.properties.each do |property|
      tr
        td = property.name
        td = property.value

= link_to 'Edit', edit_device_path(@device)
'|
= link_to 'Back', @device.area

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | KadenPortal
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      = yield